# Generated by Django 4.0 on 2021-12-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_bookpublisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPublisher',
        ),
    ]
